version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=crawler_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: crawler:0.1
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/crawler_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - APPLICATION_IMAGE_PROPERTIES_FOLDER_PATH=/app/compressedFiles/
    volumes:
      - compressed_files:/app/compressedFiles

volumes:
  postgres_data:
    name: postgres
  compressed_files:
    name: files
