spring:
  application:
    name: back-agro-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/crawler_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
  rabbitmq:
    host: localhost
    port: 5672
    username: username
    password: password
    listener:
      simple:
        default-requeue-rejected: false

application:
  producer-properties:
    min-urls-generate-producer: 10
  thread-properties:
    max-producer-count: 7
    max-consumer-count: 3
  image-properties:
    folder-path: src/main/resources/compressedFiles/
    min-size-for-scraping-kb: 10
    available-formats: png, jpeg, jpg