spring:
  application:
    name: back-agro-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/crawler_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration

application:
  image-properties:
    folder-path: src/main/resources/compressedFiles/
    size-before-compressed-kb: 5